export enum Interval {
    SEMITONE = 1,
    TONE,
    TONE_AND_HALF,
    TWO_TONES,
    TWO_TONES_AND_HALF,
    THREE_TONES,
    THREE_TONES_AND_HALF,
    FOUR_TONES,
    FOUR_TONES_AND_HALF,
    FIVE_TONES,
    FIVE_TONES_AND_HALF,
}
